### ISSUE TITLE
Excited about LLARVA! Open-source timeline query

### ISSUE THREAD

**Issue by wlxing1901** [Dantong88/LLARVA#2]
Congratulations on the outstanding LLARVA project! Your work on vision-action instruction tuning is truly groundbreaking. The performance across various robotic tasks and environments is impressive, and the use of visual traces is ingenious.

I'm excited about LLARVA's potential and wondering if you have any plans to open-source the codebase. Do you have a rough timeline for when it might be made publicly available?

Thanks for your contributions to the field!

**Comment by Dantong88** [comment]
Have some update.
