### ISSUE TITLE
some questions about training

### ISSUE THREAD

**Issue by LiHaoHN** [Dantong88/LLARVA#5]
How many GPUs did you use and how long did you train at the vision-action_instruction_pretraining stage? It looks like it should take a long time to train. Thanks for your reply!

**Comment by yuvansharma** [comment]
For the pretraining stage we used 8 NVIDIA A6000 GPUs for 2-3 weeks. We have also released our pretrained model weights (see [https://github.com/Dantong88/LLARVA/blob/main/docs/Vision-Action_Instruction_Pre-training.md]()).

**Comment by LiHaoHN** [comment]
Get it, thank you very much!
