### ISSUE TITLE
Headless mode issues

### ISSUE THREAD

**Issue by Holmes-GU** [Dantong88/LLARVA#7]
Hi, 

Thank you for the codes.  When using instruction 
"sudo apt-get install xorg libxcb-randr0-dev libxrender-dev libxkbcommon-dev libxkbcommon-x11-0 libavcodec-dev libavformat-dev libswscale-dev"
to set headless mode from your fork (https://github.com/MohitShridhar/RLBench/tree/peract#running-headless), the system returns the following information. Is it OK or what should I do to fix it? Looking forward to your help.

<img width="1429" alt="image" src="https://github.com/user-attachments/assets/2352ae0e-b4f9-4f81-9d02-4f21950b1568">

**Comment by yuvansharma** [comment]
Did you try running `sudo apt-get update` first?
