### ISSUE TITLE
unexpected output of the RLbench finetuned model

### ISSUE THREAD

**Issue by jiaming-zhou** [Dantong88/LLARVA#8]
Thanks so much to the authors for open-sourcing this work.

I followed the instructions ([RLbench's prediction script](https://github.com/Dantong88/LLARVA/blob/main/docs/Vision-Action_Instruction_Tuning.md#inference)) to evaluate the released checkpoint (https://drive.google.com/drive/folders/1uwCIFQ20a4yk5yOE073d82gELjM7_QaS) on the RLBench task, and I got some chaotic outputs (the same problem as https://github.com/Dantong88/LLARVA/issues/4#issue-2613147400),

example #1 (this is a normal output that we expect):
task: sweep dirt to the short dustpan, step:0, outputs: The next action step: [0.0032, -0.0173, 0.0002, -0.0569, 0.0004, 0.0189, 0.0229, 1.0]

example #2:
task: sweep dirt to the short dustpan, step:1, outputs: 1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,

Sincerely hope that the authors can help us verify this issue!

**Comment by Dantong88** [comment]
Hello, we never encounter the same issue when we do released test. According to our results, the ckpt should have stable output for this task. Not sure what happens, maybe you just install a latest version transformer etc, or there is some difference between your comversation template and the one we used to train the model. We are happy to give more comments if you provide more details :)
