### ISSUE TITLE
Some questions about the exps on RLBench

### ISSUE THREAD

**Issue by jiaming-zhou** [Dantong88/LLARVA#9]
Dear authors,

LLARVA is an excellent work that provides a new direction for developing VLA models in the manipulation community. And thank you for releasing the code and data. I am trying to evaluate the LLARVA model on the RLBench tasks, and I have some questions about the experiment part,

Q1: the released checkpoint is a lora-finetuned model on the sweep_to_dustpan_of_size task, however, there are a total of 18 tasks evaluated in the paper. Are these tasks all trained under a single-task setting? If not, I sincerely hope you release the checkpoint that fine-tuned on all 18 tasks;

Q2: the rlbench fine-tuning using 800 demos for each task. What effect does it have on the performance if only 100 demos are used during finetuning? (since PerAct, and RVT-1/2  both used 100 demos for training, although they used multi-view images as inputs)

**Comment by Dantong88** [comment]
Thank you for your interest and questions about LLARVA! Here are some answers:

As mentioned in the paper, all 18 tasks are fine-tuned individually using 800 demonstrations. However, each task includes multiple variations. Therefore, even though the tasks are fine-tuned individually, they encompass more than just a single "task" in practice.

Regarding the comparison to PerAct and similar approaches: while they use 100 demonstrations, we use 800 demonstrations. In our initial experiments, using fewer demonstrations resulted in suboptimal performance. LLARVA demonstrates that VLMs have the potential to perform robotic tasks when these tasks are framed as a unified VQA problem. However, compared to traditional architectures and policies specifically designed for motor control (e.g., reinforcement learning or imitation learning), LLARVA's performance still has room for improvement. We are actively exploring these improvements in our current research.

**Comment by jiaming-zhou** [comment]
Thank you very much for your prompt reply. I got the answers to both questions. Looking forward to seeing your follow-up research on this topic.
